### ISSUE TITLE
Scala Almond

### ISSUE THREAD

**Issue by orellabac** [RandomFractals/vscode-data-table#112]
is there a way to make this extension to work with Almond Scala ?

**Comment by RandomFractals** [comment]
What is Almond Scala?

This extension is designed to work with any Jupyter notebook cell outputs in VSCode that produce json, csv, or geojson data.

**Comment by orellabac** [comment]
Thanks. Almond is an scala kernel.

I was able to integrate up to a certain point. But i have some large csv do
you have a recomendation of a proper way to stream a big file ?

**Comment by RandomFractals** [comment]
@orellabac I've done some preliminary work on large data streaming in this new Tabular Data Viewer extension recently:

https://github.com/RandomFractals/tabular-data-viewer

It's not for Jupyter notebooks, but you can try it with CSV files over 1GB in size.

New release is coming this week with Perspective view, data grouping, filtering, and basic charts.

That said I will close this request as I don't plan to provide tight integration for different Jupyter notebook kernels in this renderer extension at the moment.
