### ISSUE TITLE
Installed extension, and still no option to render table with data-table? 

### ISSUE THREAD

**Issue by RollsChris** [RandomFractals/vscode-data-table#118]
Installed extension, and still no option to render table with data-table? 
i have tried the rest book examples and still no option
![image](https://user-images.githubusercontent.com/6059035/160714934-de4f84be-89db-4ef5-a890-62fc861bcf49.png)

Do i need to do anything else to get this working?

**Comment by RandomFractals** [comment]
@RedEyedDog this was patched in #114 to support new custom `text/x-json` mime type used by REST book for json outputs and will be released soon.

**Comment by RollsChris** [comment]
Ok thanks.. any idea when it will be fixed? 

Can I just ask you a quick couple questions :) 

I'm writing a custom notebook and id like to use your table to display the data.. do I need to install this extension along side mine or does the user need to have it installed? 

I presume if I just set the Output mime type to the one you support.. it will show up as a renderer? that would be grrreat 

Sorry still a nooobster with vscode extensions 

Thanks

**Comment by RandomFractals** [comment]
that issue is already fixed and will be released this week. I am wrapping up a few other things like new flat data grid addition described in #115.

You do need to install this extension in order to use them as alternative renderers in your custom notebooks. As long as you have cells that output content in the supported mime type formats, all the data table renderers in this extension should work with your custom notebooks or kernels. 

Here is the list of supported data outputs from our `package.json` renderer declarations:

```
  "displayName": "Data Table",
        "mimeTypes": [
          "application/json",
          "application/geo+json",
          "application/vnd.code.notebook.stdout",
          "application/xml",
          "text/csv",
          "text/plain",
          "text/x-json",
          "text/xml"
        ]
```

**Comment by RollsChris** [comment]
Thanks, easier than i thought then ;)

**Comment by RandomFractals** [comment]
yeah, some things are broken in the published version now, like TS notebooks & I have not tested recent .Net Interactive notebook updates, but I plan to keep this extension current and patch those issues as they arise. Some of the custom vscode notebook kernels still change frequently and are not very stable. I would recommend you use it with Py notebooks for now.

As long as you output CSV text or JSON objects from your cell, you'd be able to use current data table and summary renderers, and the new Flat Data Grid renderer added in #115 is kind of like a combo of both.

Give me a day or two to wrap up my update release. Also, feel free to share what notebooks you'd use it for.

**Comment by RollsChris** [comment]
I'm currently helping on the SQL Notebook vscode extension.. we are outputting in markup mime type with a table...its not nice and i think this would be perfect.. it should be easy to get the response into json format so lets hope its smoooth sailing :)

**Comment by RandomFractals** [comment]
btw, XPath notebooks have our data table renderers integrated for their outputs. You can see how they do it there too:

https://github.com/DeltaXML/vscode-xpath-notebook#auto-completion

**Comment by RandomFractals** [comment]
@RedEyedDog also, you can declare this ext. as a dependency for your SQL notebook vscode extension, if you'd like to have it installed automatically with your extension for your users to use.

Just add this to your ext. `package.json`:

```
	"extensionDependencies": [
		"RandomFractalsInc.vscode-data-table"
	],
``

**Comment by RollsChris** [comment]
That's great thanks I'll check it out 🤠 cheers for the insight dude

**Comment by RollsChris** [comment]
Hey i have just initiated a PR into SQL Notebooks which makes data-table a dependency, not much else to do really except change our output mime types to application/json :) 

Thanks for your help
