### ISSUE TITLE
Add notebookRenderer keyword for the new Search Marketplace prompt

### ISSUE THREAD

**Issue by mika76** [RandomFractals/vscode-data-table#121]
As mentioned in https://github.com/dotnet/interactive/issues/1950, when trying out .net interactive notebooks I used javascript and tried to return an object, but it could not be rendered and this extension did not come up with the filter: `@tag:notebookrenderer application/json`

![161013931-f5e27026-212d-44af-9c55-dba307089902](https://user-images.githubusercontent.com/229311/161217422-5023325b-a587-4f9e-95ba-a0d9017a1b70.png)
"

**Comment by RandomFractals** [comment]
@mika76 did you install the extension? That `Search Marketplace` notebook output prompt is new.

Currently, this extension is registered to render `application/json` mime type.

You can see more info about it in this issue comment: https://github.com/RandomFractals/vscode-data-table/issues/118#issuecomment-1083102082

**Comment by mika76** [comment]
@RandomFractals yeah I did, but only once @jonsequitur told me about it on the other issue. The extension search didn't find it until I searched it by name.

**Comment by RandomFractals** [comment]
I'll add `notebookrenderer` keyword in the next update. Hopefully that will work with new `Search Marketplace` prompt.

**Comment by RandomFractals** [comment]
Actually, that `notebookRenderer` keyword is already in our `package.json`: https://github.com/RandomFractals/vscode-data-table/blob/main/package.json#L37

New release is coming soon (see #120). You'll be able to see it in v1.9.0 update.
