### ISSUE TITLE
VSCode-data-table not in VSCode gallery

### ISSUE THREAD

**Issue by gbrueckl** [RandomFractals/vscode-data-table#126]
Hi, 
it seems like your extension is not in the official VSCode gallery?!
I would like to use the renderers in my VSCode extension using "extensionDependencies" or at least pointing users to this extension

or is there a good reason why it is not in the official gallery?

regards & thanks for the great extension
-gerhard

**Comment by RandomFractals** [comment]
Hi @gbrueckl,

I unpublished Data Table Renderers and a few other of my code/data viz extensions with low number of github stars and only a few K of installs from VSCode marketplace back in April. See [this twitter thread](https://twitter.com/TarasNovak/status/1519834908520337408).

I made this extension repository public again recently per request from some other devs, but currently I don't plan to republish it again in VSCode marketplace until Microsoft provides paid extension options in marketplace, or I'll get at least [10 sponsors on github](https://twitter.com/TarasNovak/status/1551220578417352706) to support future dev work on this and other open source data tools vscode extensions.

If you think your users would find these data renderers useful, you can link them to this repository and instruct them to install it from `.vsix` attached in releases:

https://github.com/RandomFractals/vscode-data-table/releases

Also, see this post in vscode dev discussions and feel free to sponsor my dev work if you find my dataViz extensions useful and would like to see some of them published again in vs marketplace: https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-3374131

After reviewing your github profile I also discovered that you are working on PowerBI & Databricks vscode tools. You can use our new monthly [Integration Sponsoring Tier](https://github.com/sponsors/RandomFractals/sponsorships?sponsor=RandomFractals&tier_id=204472&preview=false) to request new features and integrations with your tools.

**Comment by RandomFractals** [comment]
@gbrueckl I published it back in marketplace. You can use it as a dependency in your extensions and even with Jupyter notebooks in vscode web versions now. See our announcement on twitter & please consider sponsoring this dev work: 

https://twitter.com/TarasNovak/status/1560402316527894531

Thanks for including this extension and mentioning Data Preview in your Databricks vscode extension docs!
