### ISSUE TITLE
Once installed it is breaking some of the output formatting

### ISSUE THREAD

**Issue by colombod** [RandomFractals/vscode-data-table#146]
Once the extension is installed it takes over a lot of mime types.

From the following screenshot the extension is providing a renderer for stdout but not handling codes correctly

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/375556/191306607-8aef90fe-225d-4c9f-aad0-53c000081c2d.png">

This is the default renderer 

<img width="594" alt="image" src="https://user-images.githubusercontent.com/375556/191307036-8e6bf533-a512-478b-8a6a-5cafd94efedf.png">

**Comment by RandomFractals** [comment]
@colombod it doesn't take over mime types. This data renderers extension provides alternative text output view with scrollbars, unlike the built-in vscode text output extension. See our docs for details: https://github.com/RandomFractals/vscode-data-table#text-oputput-view

**Comment by RandomFractals** [comment]
Resolved in #153.
