### ISSUE TITLE
Data Grid renderer does not show list output

### ISSUE THREAD

**Issue by jmagosta** [RandomFractals/vscode-data-table#149]
If one has switched to the grid renderer any list output is not displayed. 

For instance:
![image](https://user-images.githubusercontent.com/87355/221996470-65e02227-93b6-4eef-a1ec-fb317ca2b902.png)

This happened unexpectedly -- I don't recall loading this extension, or setting the display output to data grid.   In any case returning no output for lists should not be a valid behavior.

**Comment by RandomFractals** [comment]
@jmagosta could you please share your notebook?

What type of notebook are you using and what is that list cell code?

VSCode does use built-in renderers by default, and I documented the supported notebook cell output formats in extension docs already. 

I don't think your cell output is csv, json or any of the other supported data formats.

See Features in docs for more info: https://github.com/RandomFractals/vscode-data-table#-features

**Comment by jmagosta** [comment]
The notebook is trivial.  It just a VSCode jupyter notebook -- the point is
that whatever the default renderer is that is used fails to show list
output.  Honestly, except for the fact that Databricks VSCode requires this
extension I'm not sure what the point of it is.


______________
John Mark Agosta
Palo Alto, CA
***@***.***

**Comment by amunger** [comment]
the output is an array:
```
"data": {
    "text/plain": [
        "[0, 1, 2, 3, 4]"
    ]
},
```

**Comment by jmagosta** [comment]
Yes, but it's not displayed.
______________
John Mark Agosta
Palo Alto, CA
***@***.***

**Comment by amunger** [comment]
I was responding to @RandomFractals comment
> I don't think your cell output is csv, json or any of the other supported data formats.

Also, on this -
> VSCode does use built-in renderers by default

Merely installing this extension causes this blank output to show up, so the extension's renderer is prioritized over the built-in

**Comment by gbrueckl** [comment]
so the output of that command `list(range(5))` is a text/plain as already mentioned by @amunger 
the data table renderers are mainly for displaying data frames/tables and not for text outputs like in your example.
it will be displayed the same way as any other text e.g. "My random text"
Thats what Databricks returns, a text and not a table hence your text will not be rendered properly as a list or table
if you were to use `display(df)` instead, it would output as `text/x-json` and `json/application` which will then be rendered properly using the Table Renderers

**Comment by jmagosta** [comment]
It is not true that "it will be displayed the same way as any other text "
  A list, unlike a text string or tuple results in no display at all.  This
is inconsistent.    _J

______________
John Mark Agosta
Palo Alto, CA
***@***.***

**Comment by RandomFractals** [comment]
@gbrueckl thanks for clarifying the way data table renderers work.

@jmagosta you should use built-in or other renderers for your list.

This extension is open source and you can actually see where and how cell output is handled and parsed in `getData()` in our `outputLoader.ts`: https://github.com/RandomFractals/vscode-data-table/blob/main/src/renderer/outputLoader.ts#L22

It would help if you actually included a simple notebook to reproduce your issue better. Your output screenshot doesn't even show the whole cell output rendering or anything about that list.

**Comment by jmagosta** [comment]
A list, unlike a text string or tuple results in no display at all. Merely installing this extension causes this blank output to show up, because the extension's renderer is prioritized over the built-in. This is inconsistent, confusing behavior.

**Comment by RandomFractals** [comment]
@jmagosta please read all of the above. Looks like you joined github to just troll us about this one issue, with yet a full notebook to reproduce it and logging more of your speculations without examples to run in another vscode extension I created.

I like good, critical feedback, but I don't have time reiterating what was shared and well documented already. For those reasons, I will block you from posting here.

Thank you for your vague and lacking details feedback! You can just uninstall this extension and use the built-ins as I've suggested.

**Comment by amunger** [comment]
the repro notebook is a single code cell. Running the cell with this extension installed will result in a blank output.
```
list(range(5))
```
[repro.zip](https://github.com/RandomFractals/vscode-data-table/files/10865094/repro.zip)

**Comment by gbrueckl** [comment]
so it works (in terms of displaying some text) for me:
using built-in VSCode renderer:
![image](https://user-images.githubusercontent.com/11884402/222369308-15a3a236-20ee-44f2-8b11-a095bee8e280.png)

using Data Table renderer from this extension:
![image](https://user-images.githubusercontent.com/11884402/222369394-a25906fb-af2a-4ef8-8777-5abea73f4701.png)

using Data Summary renderer from this extension
![image](https://user-images.githubusercontent.com/11884402/222369548-5956f99c-f304-4e02-9735-ab54c549b883.png)

using Flat Data Grid renderer from this extension:
![image](https://user-images.githubusercontent.com/11884402/222369650-2809ecb6-f937-478a-a88a-0b3e9491de32.png)

as I said, it is just a text thats returned by databricks and the extension tries to parse it into table as it is built for tabular visulalization. I agree that the output is useless but thats because of the input and not because of the renderer
