### ISSUE TITLE
Trying to make it work

### ISSUE THREAD

**Issue by nonoash** [RandomFractals/vscode-data-table#150]
Hello,

I've downloaded the extension on vscode and with a random jupyter notebook generated a dataframe for example, when i try to change the output presentation on clicking on the 3 dots "..." I have the RandomFractals presentation but they're all plain text and not like the ones pictured of the description.

![image](https://user-images.githubusercontent.com/116904212/222927449-28b9f869-5ef7-4d1e-a096-6e04a988f061.png)

So i'm kinda new and there must be something stupid i don't know about?
Could you help me telling me what i'm missing it make it works?

Thanks.

**Comment by RandomFractals** [comment]
@nonoash if you output json from your notebook cell, you'll be able to use flat data grid, simple data table, and data summary renderers. See Examples: https://github.com/RandomFractals/vscode-data-table#-examples
