### ISSUE TITLE
Support for multiple tables

### ISSUE THREAD

**Issue by gbrueckl** [RandomFractals/vscode-data-table#152]
we have scenarios where a notebook cell returns multiple tables which I would like to be visualized.
as of now I think thats not possible - are there any plans to support this in the future?

either using multiple custom MIME types or some specific JSON to hand over the data from the notebook to the renderer?

just an idea though

**Comment by RandomFractals** [comment]
no immediate plans to support this extra/edge case. see our comments in your original repo issue request: https://github.com/paiqo/Databricks-VSCode/issues/158#issuecomment-1560141839
