### ISSUE TITLE
Extension displays multiple stdout stream outputs in polyglot notebooks

### ISSUE THREAD

**Issue by colombod** [RandomFractals/vscode-data-table#153]
Users  are reporting this issue when the extension is installed. https://github.com/dotnet/interactive/issues/3053.

The presence of the extension causes this output:
![image](https://github.com/RandomFractals/vscode-data-table/assets/375556/8f2989f3-ce73-48ab-b9cd-e6bfc459dbbc)

**Comment by RandomFractals** [comment]
@colombod probably because your C# code cell produces 3 cell outputs when that code runs, instead of one with:

```
line 0
line 1
line 2
```

Not sure how we can help you there. Perhaps, review your console logging and outputs produced by the .net code cells.

**Comment by colombod** [comment]
stdout is supposed to be concatenated to previous cell otherwise doing `write` instead of `writeline` will produce outputs on two lines instead, also that will cause the the output cell to have more than one output block. I am not sure about the requirement of intercepting stream output types for the fata-table renderers.

**Comment by colombod** [comment]
> @colombod probably because your C# code cell produces 3 cell outputs when that code runs, instead of one with:
> 
> ```
> line 0
> line 1
> line 2
> ```
> 
> Not sure how we can help you there. Perhaps, review your console logging and outputs produced by the .net code cells.
 
@RandomFractals the quoted statement is not correct as the code produces exactly a since cell output element in the vscode extension.
This is the line stream outputs are appended to the existing one, you can review this part : https://github.com/dotnet/interactive/blob/2ca13bab0c1a4fba095802d6e5d9409112ce305d/src/polyglot-notebooks-vscode-common/src/notebookControllers.ts#L269

The code of polyglot notebook is not producing 3 outputs but appending stream types to the latest one.

Is it possible to reopen this issue?

Thank you.

**Comment by RandomFractals** [comment]
@colombod do you have a link to the standard "streamed" output in VS Code notebooks examples or documentation to resolve it, without the special and custom .net interactive, now "polyglot" notebooks internals?

**Comment by colombod** [comment]
No but that code is what the developers of jupyter extension advices to do. Can see if I can find more info for you but how to handle outputs is the responsibility of the notebook controller and it depends on requirements . For us was to be compliant with expectations from jupyter lab and python users

**Comment by vityas** [comment]
Referencing an issue I asked about in an extension that required data tables:
https://github.com/paiqo/Databricks-VSCode/issues/163

short story, installing this extension prevents cells that have print statements to behave as expected.

**Comment by gbrueckl** [comment]
has there been any update to this @RandomFractals?
As this is affecting all users that installed our Databricks Extension due to the dependency we have currently added to this extension

**Comment by RandomFractals** [comment]
I will look into patching it this week, but as you noted in your ticket there is a workaround to simply use the built-in renderer for such outputs.

**Comment by RandomFractals** [comment]
@gbrueckl & @colombod after looking more into this, I am tempted to remove my renderers from supporting `application/vnd.code.notebook.stdout` mime type, and let vscode handle it. The long text cell output rendering is much better in vscode now with the built-in output renderer. That was the only reason I added it to view scrollable text when renderers api came out and built-in renderer did not handle long outputs well.

Related config: https://github.com/RandomFractals/vscode-data-table/blob/main/package.json#L96

@gbrueckl does your extension and databricks users use `stdout` or other text and json data mime types to view tabular data with my data table renderers?

**Comment by gbrueckl** [comment]
no, we are not using `stdout` at all, we mainly use JSON and sometimes plain text

we use `text/html`, `text/plain`, `text/x-json`, `application/json`, `application/databricks-table` and `text/markdown`

**Comment by colombod** [comment]
> @gbrueckl & @colombod after looking more into this, I am tempted to remove my renderers from supporting `application/vnd.code.notebook.stdout` mime type, and let vscode handle it. The long text cell output rendering is much better in vscode now with the built-in output renderer. That was the only reason I added it to view scrollable text when renderers api came out and built-in renderer did not handle long outputs well.
> 
> 
> 
> Related config: https://github.com/RandomFractals/vscode-data-table/blob/main/package.json#L96
> 
> 
> 
> @gbrueckl does your extension and databricks users use `stdout` or other text and json data mime types to view tabular data with my data table renderers?

I think this will avoid the issue where stream are printed multiple times.

**Comment by RandomFractals** [comment]
Great! @gbrueckl & @colombod thanks for the quick follow up.

I'll remove stdout mime types from the 3 data table renderers, and hopefully that will make a much better experience for both new polyglot and databricks notebook users.

Will try to push that update this week. Thanks for your patience on this!

**Comment by RandomFractals** [comment]
so, a few things that would help us reproduce scenarios like this next time:

1. @colombod please share your test `.ipynb` next time.
2.  Would be nice if we could comment on your original issue in your repo: https://github.com/dotnet/interactive/issues/3053 (currently can't on any of the "Open at Microsoft" repos :( cc @jonsequitur
3. Your Open at Microsoft org should sponsor our extensions and issues resolutions like this as mentioned in the past since most of your new polyglot users now use it too because new Data Wrangler requires Python install and not all devs want to use it with Jupyter notebooks in code for simple tabular data display and fancy renderings our Data Table renderers provide. cc @jonsequitur

Created this Jupyter notebook to test it out:

![image](https://github.com/RandomFractals/vscode-data-table/assets/656833/2761a9e6-23fd-47f6-b186-3f6baea7fcfe)

Output rendering with built-in renderer:

![image](https://github.com/RandomFractals/vscode-data-table/assets/656833/446d5db4-90eb-4fdc-9bc3-e3a365444f23)
