### ISSUE TITLE
Change Presentation for single cell

### ISSUE THREAD

**Issue by ajshedivy** [RandomFractals/vscode-data-table#159]
@RandomFractals  I've been experimenting with this extension and Its awesome! 

One thing I've noticed is that when I change the presentation of a cell (by selecting `...`) for json for example, all cells with output type json are also re-rendered. It would be cool if I could set the presentation for a single cell to show my data with the Data Table renderer, and another output cell as a Flat Data Grid renderer. Do you know of any workarounds for something like this? Or is this even possible? Thanks! Let me know if you have any questions for me

**Comment by RandomFractals** [comment]
@ajshedivy that is not currently possible with the way VS Code notebooks render cells based on the selected output mime type. VS Code notebook associates outputs with the selected renderers by mime type for the whole notebook and does not store individual cell output renderer association selection atm.

Please log an issue in VS Code repository for that dev team to enable this functionality. Closing this as there is not much we can do on our end to mitigate it.

Been wanting to use different renderers per cell selectively for a long time too after producing a few different renderers for data tables and maps. 🤗 

P.S.: thanks for pushing this [PR](https://github.com/codefori/vscode-db2i/pull/240)! Would be good to see VS Code DB2 for IBM tools use our data table renderers as most VS Code data notebook extensions use them now.
