### ISSUE TITLE
Add subtle table cell borders

### ISSUE THREAD

**Issue by RandomFractals** [RandomFractals/vscode-data-table#59]
see #57 

Alternatively, default to table display without cell borders display for cleaner data view and let users change it via `data.table.cell.border = true` or similar setting.

Ideally, we would add `data.table` settings change handler in `extension.ts` and create `config.ts` similar to how we did it in snippets viewer for us to load this and table height setting described in #55

see: https://github.com/RandomFractals/vscode-snippets-viewer/blob/main/src/config.ts

**Comment by usernamehw** [comment]
`createRendererMessaging` requires proposed api enabled. It will be Stable after **1.59**.

To send a message, edit `package.json`:

```js
"activationEvents": [
  "onRenderer:vscode-data-table"
],
"contributes": {
    "notebookRenderer": [
      {
        "id": "vscode-data-table",
        // ...
        "requiresMessaging": "optional",// <==
      }
    ]
}
```

In `extension.ts`

```ts
const rendererMessaging = notebooks.createRendererMessaging('vscode-data-table');
rendererMessaging.onDidReceiveMessage(handleMessage);
function handleMessage(msg: any) {

}
```

In `renderer/index.ts`

```ts
context.postMessage?.('msg');
```

**Comment by RandomFractals** [comment]
let's wait till vscode v1.59 is released to implement these changes.

I'll update vscode dev dependencies and notebook api libs in #63 for now, if that helps.

**Comment by RandomFractals** [comment]
@usernamehw I am closing this since built-in vscode table styles also use alternating row bg colors and no borders either. I think doing both is too much cognitively, and not worth the extra effort for the current data table display.
